#import <PEGKit/PKParser.h>

enum {
    LYKCSS_TOKEN_KIND_COLON = 14,
    LYKCSS_TOKEN_KIND_SEMI_COLON = 15,
    LYKCSS_TOKEN_KIND_CLOSE_CURLY = 16,
    LYKCSS_TOKEN_KIND_OPEN_CURLY = 17,
};

@interface LYKCSSParser : PKParser

@end

